env:
  type: "maze"
  horizon: 30
  use_images: True
  dense_rewards: True
  max_force: 0.3
  goal_thresh: 0.03

video_model:
  type: "SVG"
  note: "svg1-5"

  image_dim: 64
  channel_dim: 3
  action_dim: 2
  data: "./saved/maze/"

  n_past: 1 # TODO: allow for n_past > 1 by changing state generation code
  n_future: 5

  rnn_size: 256
  prior_rnn_layers: 1
  posterior_rnn_layers: 1
  predictor_rnn_layers: 2
  z_dim: 10
  g_dim: 128

  beta: 0.0001
  last_frame_skip: True

  epochs: 50
  batch_size: 32 # TODO fix batchsize for video training
  lr: 0.002
  train_test_split: 0.9
  num_cores: 10

cost_model:
  ensemble_size: 5

  hidden_size: 64
  cost_reg: 0.0
  lr: 0.002