env:
  type: "maze"
  horizon: 20
  use_images: False
  dense_rewards: True
  max_force: 0.3
  goal_thresh: 0.03

dynamics_model:
  epochs: 25
  batch_size: 32 # TODO fix batchsize for video training
  lr: 0.002
  train_test_split: 0.9
  num_cores: 10

cost_model:
  hidden_size: 64
  cost_reg: 0.0
  lr: 0.002
  use_images: False

mpc:
  cem_iters: 5
  cem_pop_size: 200
  cem_elites: 20
  ensemble: False