env:
  type: "hopper"
  horizon: 40
  use_images: False
  dense_rewards: True
  max_force: 2
  goal_thresh: 0.0
  dims: [100, 100]
  state_dim: 11
  action_dim: 3

human:
  type: "hopper_human"
  same_margin: 0.005
  actual_human: False

dynamics_model:
  num_dynamics_iters: 200000
  gt_dynamics: False
  epochs: 100
  batch_size: 32
  lr: 0.0005
  train_test_split: 0.9
  num_cores: 10
  online_update_freq: 10000
  use_cached: True
  model_file: "model.pth"
mpc:
  cem_iters: 5
  cem_pop_size: 200
  cem_elites: 20
  rnd_weight: 0.1
  keep_gen_traj: 10
cost_model:
  gt_cost: False
  state_only: False
  use_images: False
  offline_demos: 0
  drex_pretrain: False
  episodes: 100
  regularization: 0.2
  hidden_dim: 512
  lr: 0.0002
  ensemble_size: 3
  query_batch_size: 5
  batch_size: 10
  query_technique: "infogain"
  num_generated_pairs: 20
  cost_steps: 1


