env:
  type: "maze"
  horizon: 30
  use_images: False
  dense_rewards: True
  max_force: 2
  goal_thresh: 0.05
  walls: True
  state_dim: 2
  action_dim: 2
human:
  type: "maze_human"
  same_margin: 0.005

dynamics_model:
  num_dynamics_iters: 120000
  gt_dynamics: False
  epochs: 50
  batch_size: 32
  lr: 0.001
  train_test_split: 0.9
  num_cores: 10
  online_update_freq: 100000
  use_cached: True
  save_obs: "obs"
  save_acs: "acs"

cost_model:
  hidden_dim: 512
  regularization: 0.0
  lr: 0.0002
  use_images: False
  episodes: 200
  offline_demos: 0
  bc_comp_mode: "same"
  bc_warm_start: False
  pretrain_epochs: 10
  state_only: True
  gt_cost: False
  ensemble_size: 3
  query_batch_size: 10
  query_technique: "infogain"
  batch_size: 10
  num_generated_pairs: 45

mpc:
  cem_iters: 5
  cem_pop_size: 200
  cem_elites: 20
  ensemble: False
  rnd_weight: 0.1
  keep_gen_traj: 10