env:
  type: "maze"
  start: "left"
  horizon: 30
  max_force: 0.6

gather_env:
  type: "maze"
  start: "left"
  horizon: 30
  max_force: 0.3

human:
  type: "maze_human"

video_model:
  type: "SVG"
  n_past: 1
  n_future: 8

  rnn_size: 256
  prior_rnn_layers: 1
  posterior_rnn_layers: 1
  predictor_rnn_layers: 2
  enc_dim: 128
  z_dim: 10

  beta: 0.001
  last_frame_skip: True

  epochs: 200
  batch_size: 64
  lr: 0.002
  train_test_split: 0.9
  num_cores: 10

visualmpc:
  iter_per_action: 5
  future_frames: 10

cost_model:
  enc_dim: 128
  hidden_dim: 128
  ensemble_size: 3

  query_technique: "infogain"
  num_generated_pairs: 1000
  query_batch_size: 20
  batch_size: 32
  regularization: 0.01 # 0.1 for normal

  hidden_size: 64
  lr: 0.002