env:
  type: "scratchitch"
  horizon: 200
  use_images: False
  dense_rewards: True
  max_force: 2
  goal_thresh: 0.0
  dims: [100, 100]
  state_dim: 4
  action_dim: 7

human:
  type: "scratchitch_human"
  same_margin: 0.005

dynamics_model:
  num_dynamics_iters: 200000
  gt_dynamics: False
  epochs: 100
  batch_size: 32
  lr: 0.0002
  train_test_split: 0.9
  num_cores: 10
  online_update_freq: 10000
  use_cached: True
  save_obs: "obs_red"
  save_acs: "acs_red"
mpc:
  cem_iters: 5
  cem_pop_size: 200
  cem_elites: 20
  ensemble: False
  rnd_weight: 0.0
  keep_gen_traj: 5
cost_model:
  gt_cost: False
  state_only: False
  use_images: False
  offline_demos: 0
  bc_warm_start: False
  episodes: 100
  regularization: 0.1
  hidden_dim: 512
  lr: 0.0002
  query_batch_size: 10
  batch_size: 10
  query_technique: "infogain"
  num_generated_pairs: 10
  ensemble_size: 3

